### ISSUE TITLE
Could not run the sample code like "Send one letter to recipient via name and address"

### ISSUE THREAD

**Issue by sourabhmalani** [digipost/digipost-api-client-dotnet#101]
Hello Team,

http://digipost.github.io/digipost-api-client-dotnet/v7.0/#uc07

We have performed all the configuration steps mentioned on above link (like Initial setup, install business certificate in certificate store and use business certificate thumbprint).

We have added the given sample code for "Send one letter to recipient via name and address".

We have replaced the given values with proper values of senderid, thumbprint and document path. It is verifying the thumbprint check.

but it is showing below errors at client.SendMessage(message) last line.

"Digipost.Api.Client.Domain.Exceptions.ClientResponseException: Error occured, check inner Error object for more information. at Digipost.Api.Client.Api.DigipostApi.ThrowNotEmptyResponseError(String responseContent) at Digipost.Api.Client.Api.DigipostApi.d__22`1.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Digipost.Api.Client.Api.DigipostApi.d__15.MoveNext()"
and
"One or more errors occurred".

Please check this and let us know how can we resolve this issue.

Regards,
Sourabh Malani
![ss_01](https://cloud.githubusercontent.com/assets/7112894/23209209/46698750-f91e-11e6-97c5-6e1dde7be4dc.jpg)

**Comment by asjafjell** [comment]
I am sorry to hear that it is not working for you. Can you please inspect the inner exception and see if the error is explained there?

**Comment by sourabhmalani** [comment]
Hello Team,

Thank you for your reply.

We have downloaded the latest package for digipost 7.2 and for log4net 2.0.7 from NuGet.
![ss_01](https://cloud.githubusercontent.com/assets/7112894/23214446/c13d4ca8-f934-11e6-8f31-d1fbe94d2e39.jpg)

Actually the certificate is installed on server and we can not debug the code.

We have tried to found the more detail about exception. We have found below exception in detail.

"Digipost.Api.Client.Domain.Exceptions.ClientResponseException: Error occured, check inner Error object for more information. at Digipost.Api.Client.Api.DigipostApi.ThrowNotEmptyResponseError(String responseContent) at Digipost.Api.Client.Api.DigipostApi.d__22`1.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Digipost.Api.Client.Api.DigipostApi.d__15.MoveNext()"

We are using below code for run the sample code. Please see attached code for more information.

Please check this and let us know what is wrong in code or how to find proper detail about exception.

If it possible, Can you please provide any test sender id and thumbprint so we can check with those detail?

Regards,
Sourabh Malani

**Comment by asjafjell** [comment]
As you can see from the following documentation at [msdn](https://msdn.microsoft.com/en-us/library/system.exception.innerexception(v=vs.110).aspx), there is a property called inner exception, so what you can do here is to log `exec.InnerException.Message` or just use log `exec`, which will give the full error message. 

If this is not working for you, I suggest testing this locally on your machine until you have a working example and then deploy this to the server.

**Comment by sourabhmalani** [comment]
Hello Team,

Thank you for your reply.

We have tried to get the proper error message and found that below exception in log file.

System.AggregateException: One or more errors occurred. ---> Digipost.Api.Client.Domain.Exceptions.ClientResponseException: Error occured, check inner Error object for more information.
   at Digipost.Api.Client.Api.DigipostApi.ThrowNotEmptyResponseError(String responseContent)
   at Digipost.Api.Client.Api.DigipostApi.<GenericSendAsync>d__22`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Digipost.Api.Client.Api.DigipostApi.<SendMessageAsync>d__15.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Digipost_Sample5.DigipostSample.Page_Load(Object sender, EventArgs e) in D:\Running Work\project result24\Digipost\Digipost_Sample5\Digipost_Sample5\DigipostSample.aspx.cs:line 42
---> (Inner Exception #0) Digipost.Api.Client.Domain.Exceptions.ClientResponseException: Error occured, check inner Error object for more information.
   at Digipost.Api.Client.Api.DigipostApi.ThrowNotEmptyResponseError(String responseContent)
   at Digipost.Api.Client.Api.DigipostApi.<GenericSendAsync>d__22`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Digipost.Api.Client.Api.DigipostApi.<SendMessageAsync>d__15.MoveNext()<---

If we run the application in local machine then it will not recognize the thumbprint and given "could not found the thumbprint" message while it works on server, so we can not test this on local machine.

Please help us to resolve this issue.

Regards,
Sourabh Malani.

**Comment by asjafjell** [comment]
The exceptions are fairly generic and since you sent a screenshot of your code, I am unable to see what line it crashes on. You can try to debug this on your local machine if you install the certificate there, or just use the constructor `DigipostClient(ClientConfig clientConfig, X509Certificate2 businessCertificate)` I bet you will find your problem within minutes. Otherwise, I would suggest using the `SendMessageAsync`-method, as using a synchronous method in a GUI will almost certainly cause a deadlock as the GUI is waiting for the call to complete, and the call is waiting for the GUI thread to release it's control, which will never happen.

**Comment by sourabhmalani** [comment]
Hello Team,

Thank you for your reply.

We have tried with "SendMessageAsync" method, but it is throwing the same exception.

System.AggregateException: One or more errors occurred. ---> Digipost.Api.Client.Domain.Exceptions.ClientResponseException: Error occured, check inner Error object for more information.
at Digipost.Api.Client.Api.DigipostApi.ThrowNotEmptyResponseError(String responseContent)
at Digipost.Api.Client.Api.DigipostApi.d__221.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Digipost.Api.Client.Api.DigipostApi.<SendMessageAsync>d__15.MoveNext() --- End of inner exception stack trace --- at System.Threading.Tasks.Task1.GetResultCore(Boolean waitCompletionNotification)
at Digipost_Sample5.DigipostSample.Page_Load(Object sender, EventArgs e) in D:\Running Work\project result24\Digipost\Digipost_Sample5\Digipost_Sample5\DigipostSample.aspx.cs:line 42
---> (Inner Exception #0) Digipost.Api.Client.Domain.Exceptions.ClientResponseException: Error occured, check inner Error object for more information.
at Digipost.Api.Client.Api.DigipostApi.ThrowNotEmptyResponseError(String responseContent)
at Digipost.Api.Client.Api.DigipostApi.d__22`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Digipost.Api.Client.Api.DigipostApi.d__15.MoveNext()<---

We are using below code for this with sender id and thumbprint. Please see below image for more information.

![ss_01](https://cloud.githubusercontent.com/assets/7112894/23404576/adf0f306-fddb-11e6-8e85-81cee7aa38ca.jpg)

We have not found any sample example with DigipostClient(ClientConfig clientConfig, X509Certificate2 businessCertificate).  What should we need to specify for this X509Certificate2 businessCertificate ?

If possible please specify any working sample code here, so we can replace the sender id and thumbprint and then we can try to run.

Please help us to resolve this issue.

Regards,
Sourabh Malani

**Comment by asjafjell** [comment]
Please see documentation [here](http://digipost.github.io/digipost-api-client-dotnet/v7/#install-and-use-business-certificate) for loadining business certificate from file. Please test locally and debug before posting more of the same exceptions, we can not debug your code for you. This is your responsibility. Good luck!

**Comment by sourabhmalani** [comment]
Hello Team,

Thank you for your reply.

We have added code for X509Certificate2 as mentioned in given document link. 

We have specified the SendMessageAsync method for client object.

Now it is working and showing success message.

Thank for all you support.

Regards,
Sourabh Malani.

**Comment by asjafjell** [comment]
No worries! Great to hear that you got it working!
