### ISSUE TITLE
Litt merkelig feilmelding

### ISSUE THREAD

**Issue by hdsoftware** [digipost/digipost-api-client-dotnet#113]
Når jeg skal prøve å teste Fallback2Print får jeg konsekvent denne:
 System.Xml.XmlException: Xml was invalid. Stopped sending message. Feilmelding: 'Elementet http://api.digipost.no/schema/v7:organisation-number er ugyldig - Verdien  er ugyldig i henhold til datatypen String - Den faktiske lengden er ikke lik den angitte lengden.'
   ved Digipost.Api.Client.Api.DigipostApi.SendMessage(IMessage message)
   ved Digipost.Api.Client.DigipostClient.SendMessage(IMessage message)

Nå er jo dette fortsatt i mitt testmiljøet, og jeg har en mistanke om at det kan være årsaken.  Grunnen til denne mistanken er at jeg også får denne meldingen hvis jeg prøver å sende på vegne av oss selv.  Snakket med Fredrik Bach om det den gangen, og sa at jeg sendte inn vår ID både som sender og avsender (vi er jo et "relé"). Han sier det kommer av at "vi ikke har avtale med at noen skal sende på vegne av oss". Dette gir selvsagt mening..

Det jeg stusser på er innholdet i feilmeldingen - litt vel kryptisk vil jeg si og fryktelig vanskelig å forholde seg til i test øyemed.. Hadde jo vert betryggende å heller fått en tilbakemelding som sier noe om hva som faktisk er problemet slik at jeg kan ta det med ro å tenke "Dette funker når jeg bytter til produksjon"

**Comment by asjafjell** [comment]
Heisann, @hdsoftware!

Funksjonaliteten skal i utgangspunktet være den samme i produksjon og testmiljøer, men avvik kan selvfølgelig forekomme. For at vi skal se på denne så trenger vi litt mer informasjon.
1. Hvilken versjon av klienten bruker du.
2. Ble litt forvirret av avsnitt to. Sier du at du får feil når du sender på vegne av deg selv nå, eller at du gjorde det tidligere når du sendte på vegne av noen dere sender på vegne av? Det skal nå i  siste versjon være mulig å sende på vegne av seg selv. Det var en bug i tidligere versjoner som kunne gi en feilmelding som var utydelig. Mulig det er den du nevner nå, og hvis det stemmer så er det fikset i [versjon 8](https://github.com/digipost/digipost-api-client-dotnet/releases/tag/v8.0.0)

**Comment by hdsoftware** [comment]
Jeg lurer på om dette faktisk er noe helt annet.  Jeg ser at jeg sender inn NULL i Adresselinje3 fordi jeg aldri setter den.  Skal teste og se om det faktisk er derfor..

**Comment by hdsoftware** [comment]
nope.  Var ikke det gitt.

Men har funnet det ut.  Det var jeg som ikke brukte rett recipient metode.  Jeg så plutselig at FallbackToPrint eksemplet brukte RecipientByNameAndAddress(x,y,z,a). Måtte skrive om litt fordi jeg hadde forenklet dette slik at jeg sendte inn data til min egen metode som tar imot vår "kontakt" objekt. Så analyserte jeg typen etter hva som ble sendt inn og i de aller fleste tilfeller har vi person nummer registrert slik at den kom aldri ned til "ByNameAndAddress".  Byttet til å bruke denne spesifikt i Fallback2Print og dermed sklei det bedre...

**Comment by asjafjell** [comment]
Supert at det ordnet seg!
