### ISSUE TITLE
Digipost Inbox Fetch

### ISSUE THREAD

**Issue by hdsoftware** [digipost/digipost-api-client-dotnet#115]
Heisan...
Dere har innført Inbox API og dette bringer et par tanker:
Fetch metoden tar to INTer som parametere, OFFSET og LIMIT.
Er OFFSET i dette tilfellet referert til ID på InboxDocument record ?

Altså, vil FETCH(0, 100) gi potensielt 100 records der ID er fra 0 til 99, eller kan det forekomme huller i denne serien ?  

Årsaken til spørsmålet er fordi jeg trenger å lese "Alle nye poster" og siden dere ikke har dette så må jeg lage logikk rundt dette.

**Comment by asjafjell** [comment]
Heisann! Dette finner vi ut av! @froden er godt skikket til å svare på dette spørsmålet.

**Comment by froden** [comment]
Hei! Inbox-kallet gir en liste av dokumenter sortert på leveringstidspunkt. `offset` er start-index i denne listen og `limit` er maks antall dokumenter som skal returneres. `offset` og `limit` er derfor ikke koblet til `id` (som er dokumentets unike id). For én brukerkonto vil det kunne være store huller i rekken av id-verdier.

`offset` og `limit` er tenkt brukt til paginering slik at man først henter de første 100 og deretter de neste 100 osv. Skulle det komme (f.eks. 2) nye dokumenter mellom man henter de første 100 og de neste 100 vil det bli 2 dokumenter overlapp når man setter `offset=100, limit=100`. Hvis man ønsker å unngå å prosessere disse på nytt, er det best å holde rede på hvilke man allerede har prosessert ved å lagre `id`-en til de dokumentene man med sikkerhet vet at man er ferdig med. Da vil man trygt kunne prosessere hele listen på nytt skulle en feil oppstå.

Når man er sikker på at man har lagret og ikke lenger trenger å ha dokumentene i Digipost, kan de slettes med metoden `Task DeleteDocument(InboxDocument document);`

**Comment by hdsoftware** [comment]
Ja, hadde en prat med Fredrik Bach i går og fikk vel samme beskjeden.  

Det betyr jo at jeg må lese inn hele innboksen hver gang jeg skal synke innholdet lokalt.  Greit nok det altså, men ser jo for meg lengre transaksjoner etter som tiden går og inboksen øker.  Er jo noen der ute som ønsker å bruke inboksen sin som "fjernlagring" og vet at noen av kundene våre produserer tusenvis av dokumenter på kort tid.  Men greit nok.  Betyr bare at jeg må lage litt mere logikk en først håpet på :-)

**Comment by asjafjell** [comment]
Det er mange løsninger her, men én løsning vil være å hente f.eks 100 og 100 til du støter på en du har sett før. Da vet du at du har kommet til gamle dokumenter. Da vil mengden du må hente ned være avhengig av hvor lenge siden sist du hentet ned dokumenter, og ikke størrelsen på innboksen, men det fordrer selvfølgelig at du selv har kontroll på hvilke du har behandlet.

**Comment by hdsoftware** [comment]
Heisan, der kom det info som ikke står noen sted ;-)
Så det betyr at Fetch alltid leverer det som er nyest først.  Takker!  Det forandrer jo alt
Da er det en enkel sak å synke....

**Comment by asjafjell** [comment]
Dokumentasjonen er veldig tynn her fordi det er relativt ny funksjonalitet. Etter denne diskusjonen så blir vi å oppdatere dokumentasjonen for å bedre forklare hvordan dette kan gjøres. Som @froden nevnte så er de sortert på leveringstidspunkt, så dette bør være grei skuring, ja! 💃

**Comment by hdsoftware** [comment]
Strålende :-)
