### ISSUE TITLE
Hva må være tilstede i InboxDocument objektet for at FetchDocument skal virke ?

### ISSUE THREAD

**Issue by hdsoftware** [digipost/digipost-api-client-dotnet#116]
Årsaken til spørsmålet er at jeg kan serialisere InboxDocument objektet og lagre dette i databasen for så å deserialisere og kjøre FETCHDOCUMENT,  eller holder det med å tilordne ID'n ?

**Comment by asjafjell** [comment]
Hva har du testet?

**Comment by hdsoftware** [comment]
ingenting, er midt i engine design på servicen min så jeg har ikke gjort noen tester rundt dette enda.  Er bare tanker som dukker opp mens jeg designer mitt eget og derfor jeg spør. Kan selvsagt lage en test platform rundt dette og se hva som skjer...

**Comment by asjafjell** [comment]
Det kan ofte være nyttig å bare prøve seg fram eller bare ta en kikk i koden. Som du kan se av [denne kodelinjen roten av Inbox-funksjonaliteten](https://github.com/digipost/digipost-api-client-dotnet/blob/dev/Digipost.Api.Client.Inbox/Inbox.cs#L38) så er det kun ID du trenger.

**Comment by hdsoftware** [comment]
Et veldig bra poeng ;-)
Takker for tipset.  Klart koden avslører mye...

**Comment by asjafjell** [comment]
Det kan ofte være litt overveldende å lese kode andre har skrevet, men det gir deg mye innsikt og er god læring. 💃

Ikke nøl med å spørre om det skulle være noe du er veldig usikker på.

**Comment by hdsoftware** [comment]
Veldig nyttig tips faktisk!!  Ser at jeg kan med enkle grep utvide klassen med nye metoder for å henvise til andre subfolders!!!  Det er jo kult.  Regner med dere også etter hvert gir mulighet til å opprette subfolders via API
