### ISSUE TITLE
Office DOCM format

### ISSUE THREAD

**Issue by hdsoftware** [digipost/digipost-api-client-dotnet#117]
Heisan...  Vi distribuerer DOCM formatet med vår programvare.  Programmet feiler når vi sender et slikt dokument.  Går jo ut ifra at dette er et format dere ikke har på godkjenningslisten, men vil det bli det ?
Eller er det slik at dere anser macro enablede dokumenter som risikofylte dokumenter  og dermed ikke gyldig?

**Comment by asjafjell** [comment]
Heisann, @hdsoftware.

Du har helt rett. Feilmeldingen kommer fordi vi ikke godkjenner dette formatet. Vi gjør kontinuerlig en vurdering på hvilke formater vi anser som trygge, og dessverre er ikke _DOCM_ en av de. Det er ingen planer for øyeblikket for å godkjenne et slikt format. 

Håper det gav et klart svar på spørsmålet ditt, selv om det ikke var det svaret du håpet på.

**Comment by hdsoftware** [comment]
Ja, det gjorde det.  Jeg må med andre ord skrive litt i programmet sånn at vi kan konvertere.  Det blir helt umulig for oss å ikke støtte DOCM da alle blankett leverandører leverer sine standard blanketter i nettop DOCM


Mvh
Ole Morten Heien
Advisor AS

Fra: Aleksander Sjåfjell [mailto:notifications@github.com]
Sendt: mandag 21. august 2017 12.26
Til: digipost/digipost-api-client-dotnet <digipost-api-client-dotnet@noreply.github.com>
Kopi: Ole Morten Heien <omheien@advisor.no>; Mention <mention@noreply.github.com>
Emne: Re: [digipost/digipost-api-client-dotnet] Office DOCM format (#117)


Heisann, @hdsoftware<https://github.com/hdsoftware>.

Du har helt rett. Feilmeldingen kommer fordi vi ikke godkjenner dette formatet. Vi gjør kontinuerlig en vurdering på hvilke formater vi anser som trygge, og dessverre er ikke DOCM en av de. Det er ingen planer for øyeblikket for å godkjenne et slikt format.

Håper det gav et klart svar på spørsmålet ditt, selv om det ikke var det svaret du håpet på.
