### ISSUE TITLE
Re issue: WaitingForActivation - error msg.

### ISSUE THREAD

**Issue by UBDevelop** [digipost/digipost-api-client-dotnet#126]
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Text;
using System.Web;
using System.Web.Mvc;
using System.Threading.Tasks;
using Digipost.Api.Client.Common;
using Digipost.Api.Client;
using System.Runtime.InteropServices;
using System.Drawing.Printing;
using System.Security.Cryptography;

namespace TestDigiPost.Controllers
{
    public class DefaultController : Controller
    {
        // GET: Default
        public ActionResult Index()
        {
            GetDigipostData();
            
            return View();
        }
        
        protected dynamic GetDigipostData()
        {
            try
            {              
                    //client configuration
                    var broker = new Broker(2162xxxx);
                    var sender = new Sender(2162xxxx);
                    var clientConfig = new ClientConfig(broker, Digipost.Api.Client.Common.Environment.Production);
                    var client = new DigipostClient(clientConfig, thumbprint: "c2 75 0a f5 aa fe 8e 47 6f 19 6b 39 e8 29 f2 28 df cb c3 03");

                    //get document inbox
                    var inbox = client.GetInbox(sender);
                    var first100 = inbox.Fetch();
                    var next200 = inbox.Fetch(offset: 0, limit: 100);//offset: 0 && limit: 100
                
                    return null;
            }
            catch (WebException e)
            {
                
                return null;
            }

        }
}
}

**Comment by UBDevelop** [comment]
![pum issue](https://user-images.githubusercontent.com/33904285/33216517-766fe536-d134-11e7-9c92-1a5904add29a.png)

**Comment by asjafjell** [comment]
Hi! 

I would recommend inspecting what type `next200` is, and use this to infer what you need to do to get the result.

**Comment by UBDevelop** [comment]
Hi we have tested that as well same result, WaitingForActivation.
May it be due to the cert used from Digipost not being activated or the account

**Comment by UBDevelop** [comment]
I have taken the source from the site: http://digipost.github.io/digipost-api-client-dotnet/v8/#receivemessages
The problem i am facing is that i am getting status as "Waiting for Activation", I am attaching the screenshot of it.
Is there any setting to enable API from your end or may be in our test account? 
If possible, 
Please do  give me a proper guideline for it. So we can verify if anything is missing.

**Comment by asjafjell** [comment]
This has nothing to do with our library. I suggest that you expand `var` to variable type and read up a bit on [async/await](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/await). I bet it will get you somewhere in no time 😌.
