### ISSUE TITLE
V8.2 har manglende avhengigheter

### ISSUE THREAD

**Issue by hdsoftware** [digipost/digipost-api-client-dotnet#127]
Årsak til oppgradering er fordi dere har innført Appointment.
1. Eksisterende kode kode slutter å kompilere fordi det forventes en referanse til IDataType som skal ligge under `Digipost.API.Client.DataTypes`. Denne finnes ikke hos meg.  Når jeg ber VS finne løsning blir jeg henvist til å hente inn eksternt bibliotek.  Noe feil i NUGET-komponenten?

2. Eksempelkoden deres sier
```    
var app = New Appointment(....
```

Dette finnes heller ikke.  Appointment er ingen klasse, eller har ingen konstruktør.  Jeg kan se en klasse "appointment" under `Digipost.Api.Client.Xsd`, men denne har ingen konstruktør som tar imot noe slik som eksemplet deres.

Ser at dere også har lagt ut en beta av 8.2.108, men antar dette ikke skal brukes.  Jeg har ikke testet den så jeg vet ikke om dette endrer noe.

**Comment by asjafjell** [comment]
Heisann! 

Dette er en glipp fra oss! Vi har gjort noe galt ved pakking av .Nuget-pakke. En fiks kommer i løpet av dagen.

**Comment by hdsoftware** [comment]
Toppers :-)  
Da avventer jeg...

**Comment by SindreNordbo** [comment]
Hei @hdsoftware , vi har lansert en ny beta-versjon som vi tror løser dette problemet. Du kan installere siste beta:

> `Install-Package digipost-api-client -Version 8.2.0.108-beta`

Gi oss gjerne tilbakemelding på om denne versjonen virker.

**Comment by hdsoftware** [comment]
Nå har jeg prøvd 8.2.0.128-beta
Får fortsatt disse problemene
Sier fortsatt at jeg må referere til Digipost.Api.Client.Datatypes.
Gikk tilbake til 8.1.0 og alt er ok igjen.

**Comment by hdsoftware** [comment]
Rettelse.  Jeg prøvde en gang til og av en eller annen grunn er det annerledes nå.

Ser ut til å funke.
