### ISSUE TITLE
How can I add some custom information to the email sending using digipost signature API to the signers.

### ISSUE THREAD

**Issue by hardikCIS** [digipost/digipost-api-client-dotnet#133]
How can I add some custom information to the email sending using digipost signature API to the signers.
![image](https://user-images.githubusercontent.com/36002383/37148868-ef6dc1c4-22f1-11e8-8336-2efc0c1a445a.png)

**Comment by asjafjell** [comment]
Hi! This is still the wrong repo for posting these issues. Please post in https://github.com/digipost/signature-api-client-dotnet/ and we will look into it.
