### ISSUE TITLE
Hjelp til feilmelding

### ISSUE THREAD

**Issue by hdsoftware** [digipost/digipost-api-client-dotnet#138]
Har flyttet vår digipost service til en ny server og alt ser til synelatende helt korrekt ut.  Jeg får gjort alle ting som oppslag/søk o.s.v. men når jeg prøver å sende så får jeg følgende:

 System.AggregateException: One or more errors occurred. ---> Digipost.Api.Client.Common.Exceptions.ClientResponseException: Error occured, check inner Error object for more information.
   at Digipost.Api.Client.Common.Utilities.RequestHelper.ThrowNotEmptyResponseError(String responseContent)
   at Digipost.Api.Client.Common.Utilities.RequestHelper.<Send>d__9`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Digipost.Api.Client.Api.SendMessageApi.<SendMessageAsync>d__7.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Digipost.Api.Client.Api.SendMessageApi.SendMessage(IMessage message)
   at Digipost.Api.Client.DigipostClient.SendMessage(IMessage message)

**Comment by asjafjell** [comment]
Heisann! Om biblioteket fungerte på gammel server, men ikke ny server, så ligger ikke problemet hos oss men hos dere. Da anbefaler jeg å sjekke brannmurinnstillinger o.l. Det vil aldri være noen egenskaper ved vårt bibliotek som gjør at det ikke fungerer på en ny server.

**Comment by hdsoftware** [comment]
Ja, jeg skjønner jo det, men håpet kanskje du/dere kunne indikere og kaste lys over hva jeg skulle se etter angående exception meldingen.  Dere vet jo hva som eventuelt kaster denne og hvorfor.

**Comment by asjafjell** [comment]
Nei, det er akkurat det som er poenget her. Vi vet ikke hva som er galt. Du har hatt en fungerende, kjørende applikasjon. Når du da har flyttet den til en server så er det de endringene _du_ har gjort som har ført til at det ikke fungerer. Da må du debugge i forhold til dette. Hvis du leser feilmeldingen så ser du at den er helt generisk og gir null informasjon. Enten blir feilmeldingen spist opp lengre inn i vår applikasjon, og da kan du jo debugge og finne ut hvor dette er, eller så sender du ikke hele feilmeldingen til oss. Et tips er å sjekke brannmurinnstillinger o.l., som jeg nevnte tidligere. Men her må du uansett debugge for å finne roten til feilmeldingen.

**Comment by hdsoftware** [comment]
Hmmm.  Da må det være noe jeg ikke helt skjønner.  Betyr det at nettverks transporten er forskjellig fra SendMessage til Identify ?  Det gir jo ikke noe mening.  Jeg har kunn ett sted der jeg oppretter en klient til APIet og denne funksjonaliteten er den samme enten jeg sender eller søker, eller gjør andre ting.  Er det ikke litt merkelig at en brannmur kan gjøre forskjell på disse ?
Men ok, da får jeg se på dette med andre øyne og lete med lys og lykte 😊
Takker for forsøket i alle fall …

Mvh ole..

Fra: Aleksander Sjåfjell <notifications@github.com>
Sendt: fredag 30. november 2018 12:13
Til: digipost/digipost-api-client-dotnet <digipost-api-client-dotnet@noreply.github.com>
Kopi: Ole Morten Heien <omheien@advisor.no>; Author <author@noreply.github.com>
Emne: Re: [digipost/digipost-api-client-dotnet] Hjelp til feilmelding (#138)


Nei, det er akkurat det som er poenget her. Vi vet ikke hva som er galt. Du har hatt en fungerende, kjørende applikasjon. Når du da har flyttet den til en server så er det de endringene du har gjort som har ført til at det ikke fungerer. Da må du debugge i forhold til dette. Hvis du leser feilmeldingen så ser du at den er helt generisk og gir null informasjon. Enten blir feilmeldingen spist opp lengre inn i vår applikasjon, og da kan du jo debugge og finne ut hvor dette er, eller så sender du ikke hele feilmeldingen til oss. Et tips er å sjekke brannmurinnstillinger o.l., som jeg nevnte tidligere. Men her må du uansett debugge for å finne roten til feilmeldingen.

**Comment by asjafjell** [comment]
Jeg skulle gjerne hjulpet deg mer om du kom med mer informasjon. Slik issuet står seg så virker det som du bare har sendt oss feilmeldingen med én gang det feilet uten å ha sjekket det nærmere ut selv. Men det er ikke noe i den feilmeldingen som gjør at jeg kan finne ut noe på vår side. Her må du bare forberede deg på å skitne til fingrene og debugge litt selv.

Aleksander Sjåfjell
Utvikler og Teamleder i Bekk

+47 45 60 12 12
aleksander.sjafjell@bekk.no<mailto:aleksander.sjafjell@bekk.no>



On 30 Nov 2018, at 12:32, hdsoftware <notifications@github.com<mailto:notifications@github.com>> wrote:

Hmmm. Da må det være noe jeg ikke helt skjønner. Betyr det at nettverks transporten er forskjellig fra SendMessage til Identify ? Det gir jo ikke noe mening. Jeg har kunn ett sted der jeg oppretter en klient til APIet og denne funksjonaliteten er den samme enten jeg sender eller søker, eller gjør andre ting. Er det ikke litt merkelig at en brannmur kan gjøre forskjell på disse ?
Men ok, da får jeg se på dette med andre øyne og lete med lys og lykte 😊
Takker for forsøket i alle fall …

Mvh ole..

Fra: Aleksander Sjåfjell <notifications@github.com<mailto:notifications@github.com>>
Sendt: fredag 30. november 2018 12:13
Til: digipost/digipost-api-client-dotnet <digipost-api-client-dotnet@noreply.github.com<mailto:digipost-api-client-dotnet@noreply.github.com>>
Kopi: Ole Morten Heien <omheien@advisor.no<mailto:omheien@advisor.no>>; Author <author@noreply.github.com<mailto:author@noreply.github.com>>
Emne: Re: [digipost/digipost-api-client-dotnet] Hjelp til feilmelding (#138)


Nei, det er akkurat det som er poenget her. Vi vet ikke hva som er galt. Du har hatt en fungerende, kjørende applikasjon. Når du da har flyttet den til en server så er det de endringene du har gjort som har ført til at det ikke fungerer. Da må du debugge i forhold til dette. Hvis du leser feilmeldingen så ser du at den er helt generisk og gir null informasjon. Enten blir feilmeldingen spist opp lengre inn i vår applikasjon, og da kan du jo debugge og finne ut hvor dette er, eller så sender du ikke hele feilmeldingen til oss. Et tips er å sjekke brannmurinnstillinger o.l., som jeg nevnte tidligere. Men her må du uansett debugge for å finne roten til feilmeldingen.

**Comment by hdsoftware** [comment]
Hehe, ikke mye jeg får debugget på her altså 😊  Det er jo .net biblioteket deres som kaster exceptionen og det er jo langt vekk fra min kode.  Men jeg kan jo bruke DotPeek og lage C# kode av assembliet deres så skal jeg altids få fulgt koden og se hva som feiler..
For orden skyld så skal du selvsagt få hele exceptionen med hele stacken, men det jeg gav deg var fra mitt kall inn i deres API så jeg tror ikek det hjelper nevneverdig mer.

2018-11-30 10:13:16.9596 ERROR Something went wrong
 System.AggregateException: One or more errors occurred. ---> Digipost.Api.Client.Common.Exceptions.ClientResponseException: Error occured, check inner Error object for more information.
   at Digipost.Api.Client.Common.Utilities.RequestHelper.ThrowNotEmptyResponseError(String responseContent)
   at Digipost.Api.Client.Common.Utilities.RequestHelper.<Send>d__9`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Digipost.Api.Client.Api.SendMessageApi.<SendMessageAsync>d__7.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Digipost.Api.Client.Api.SendMessageApi.SendMessage(IMessage message)
   at Digipost.Api.Client.DigipostClient.SendMessage(IMessage message)
   at Advisor.Services.Server.ExternalServices.AdvDigipost.Engine.SendLetter(User u, Document pDocument, Contact pRecipient, Contact pSender, Boolean pIsInvoice, Decimal pInvoiceAmount, String pInvoiceAccount, Nullable`1 pInvoiceDueDate, String pInvoiceKid, Document[] pAttachments, Nullable`1 pDeliveryTime, List`1 pSmsAfterHours, List`1 pSmsOnTimes, Boolean pFallbackToPrint, PostType pPostType, Boolean pPrintColors, Boolean pUseAuthentication, AuthenticationLevel pAauthenticationLevel, Boolean pSensitive, Boolean pUseNorwegianHeltNetwork, MessageTag pMessageTag) in C:\Data\Dev\Apps\Advisor\VisualStudio\Advisor.Services.Server.ExternalServices.Digipost\Engine.cs:line 480
---> (Inner Exception #0) Digipost.Api.Client.Common.Exceptions.ClientResponseException: Error occured, check inner Error object for more information.
   at Digipost.Api.Client.Common.Utilities.RequestHelper.ThrowNotEmptyResponseError(String responseContent)
   at Digipost.Api.Client.Common.Utilities.RequestHelper.<Send>d__9`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Digipost.Api.Client.Api.SendMessageApi.<SendMessageAsync>d__7.MoveNext()<---

Mvh ole..

Fra: Aleksander Sjåfjell <notifications@github.com>
Sendt: fredag 30. november 2018 12:38
Til: digipost/digipost-api-client-dotnet <digipost-api-client-dotnet@noreply.github.com>
Kopi: Ole Morten Heien <omheien@advisor.no>; Author <author@noreply.github.com>
Emne: Re: [digipost/digipost-api-client-dotnet] Hjelp til feilmelding (#138)

Jeg skulle gjerne hjulpet deg mer om du kom med mer informasjon. Slik issuet står seg så virker det som du bare har sendt oss feilmeldingen med én gang det feilet uten å ha sjekket det nærmere ut selv. Men det er ikke noe i den feilmeldingen som gjør at jeg kan finne ut noe på vår side. Her må du bare forberede deg på å skitne til fingrene og debugge litt selv.

Aleksander Sjåfjell
Utvikler og Teamleder i Bekk

+47 45 60 12 12
aleksander.sjafjell@bekk.no<mailto:aleksander.sjafjell@bekk.no>



On 30 Nov 2018, at 12:32, hdsoftware <notifications@github.com<mailto:notifications@github.com>> wrote:

Hmmm. Da må det være noe jeg ikke helt skjønner. Betyr det at nettverks transporten er forskjellig fra SendMessage til Identify ? Det gir jo ikke noe mening. Jeg har kunn ett sted der jeg oppretter en klient til APIet og denne funksjonaliteten er den samme enten jeg sender eller søker, eller gjør andre ting. Er det ikke litt merkelig at en brannmur kan gjøre forskjell på disse ?
Men ok, da får jeg se på dette med andre øyne og lete med lys og lykte 😊
Takker for forsøket i alle fall …

Mvh ole..

Fra: Aleksander Sjåfjell <notifications@github.com<mailto:notifications@github.com>>
Sendt: fredag 30. november 2018 12:13
Til: digipost/digipost-api-client-dotnet <digipost-api-client-dotnet@noreply.github.com<mailto:digipost-api-client-dotnet@noreply.github.com>>
Kopi: Ole Morten Heien <omheien@advisor.no<mailto:omheien@advisor.no>>; Author <author@noreply.github.com<mailto:author@noreply.github.com>>
Emne: Re: [digipost/digipost-api-client-dotnet] Hjelp til feilmelding (#138)


Nei, det er akkurat det som er poenget her. Vi vet ikke hva som er galt. Du har hatt en fungerende, kjørende applikasjon. Når du da har flyttet den til en server så er det de endringene du har gjort som har ført til at det ikke fungerer. Da må du debugge i forhold til dette. Hvis du leser feilmeldingen så ser du at den er helt generisk og gir null informasjon. Enten blir feilmeldingen spist opp lengre inn i vår applikasjon, og da kan du jo debugge og finne ut hvor dette er, eller så sender du ikke hele feilmeldingen til oss. Et tips er å sjekke brannmurinnstillinger o.l., som jeg nevnte tidligere. Men her må du uansett debugge for å finne roten til feilmeldingen.

**Comment by asjafjell** [comment]
Bra plan det der!

**Comment by hdsoftware** [comment]
Og da har jeg kommet frem til hva som feiler, etter en ganske så lang debug runde.  Noen hadde greid å få inn tomme dokument filer i test systemet samt at filens extension var borte.  Med andre ord, filer som har navn av typen "abc123xyz." og har null bytes størrelse

Hadde det ikke vært en ide om dere hadde hatt et minimum av errorsjekk i biblioteket deres sånn at vi som skal bruke det slipper å disassemble programmene deres for å forstå hva som egentlig er problemet
Eller er dere fornøyd med feilmeldingen deres som lyder slik:

System.AggregateException: One or more errors occurred. ---> Digipost.Api.Client.Common.Exceptions.ClientResponseException: Error occured, check inner Error object for more information.
   at Digipost.Api.Client.Common.Utilities.RequestHelper.ThrowNotEmptyResponseError(String responseContent)
   at Digipost.Api.Client.Common.Utilities.RequestHelper.<Send>d__9`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Digipost.Api.Client.Api.SendMessageApi.<SendMessageAsync>d__7.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()

Mvh ole..

Fra: Aleksander Sjåfjell <notifications@github.com>
Sendt: fredag 30. november 2018 14:15
Til: digipost/digipost-api-client-dotnet <digipost-api-client-dotnet@noreply.github.com>
Kopi: Ole Morten Heien <omheien@advisor.no>; Author <author@noreply.github.com>
Emne: Re: [digipost/digipost-api-client-dotnet] Hjelp til feilmelding (#138)


Bra plan det der!

**Comment by asjafjell** [comment]
Det er klart at det alltid er rom for forbedringer. Det er mye feilsjekking på ting som kan endre seg i forhold til servervalidering, og i noen tilfeller er det nok litt tynt på klientsidevalidering. Antagelsen vår har bare vært at man har kontroll på data som går inn i klienten. 

Det er bare en håndfull objekter som sendes inn til klienten og jeg vil påstå at en litt lettbeint manuell debugging ville ha vist ved inspisering at du sender inn nullobjekter. Når det er sagt så er det vanlig praksis når man gjør validering av data at man antar at dataene ikke er `null`, for hvis ikke må man nullsjekke hver eneste parameter til alle metoder og skrive fornuftige feilmeldinger for det så blir det dårlig kode. Vi validerer f.eks. at det faktisk er en PDF selv om du sier at det er av type `PDF`, fordi det er en vanlig feil å sende inn feil dokument. Men å sjekke at det ikke er `null` har vi ikke sett på som nødvendig, med samme argumentasjon som jeg brukte over.  

Derfor, hvis du har et testsystem så bør du selv sørge for å validere data derfra før du sender det videre, eller så kan du komme med en Pull Request på biblioteket. Det er open source og vi tar gjerne imot endringsforespørsler.

En liten gladnyhet på slutten er at siste versjon av klientbiblioteket støtter dotnet-core og om ikke alt for lenge så skal vi få med debug assemblies der slik at man ikke trenger å gjøre slik som du gjør nå. 

Håper dette ga deg svar på hvorfor det er som i dag.

**Comment by hdsoftware** [comment]
Ja, det blir bra.
Takker for bistand i alle fall a 😊


Mvh ole..

Fra: Aleksander Sjåfjell <notifications@github.com>
Sendt: tirsdag 4. desember 2018 14:45
Til: digipost/digipost-api-client-dotnet <digipost-api-client-dotnet@noreply.github.com>
Kopi: Ole Morten Heien <omheien@advisor.no>; Author <author@noreply.github.com>
Emne: Re: [digipost/digipost-api-client-dotnet] Hjelp til feilmelding (#138)


Det er klart at det alltid er rom for forbedringer. Det er mye feilsjekking på ting som kan endre seg i forhold til servervalidering, og i noen tilfeller er det nok litt tynt på klientsidevalidering. Antagelsen vår har bare vært at man har kontroll på data som går inn i klienten.

Det er bare en håndfull objekter som sendes inn til klienten og jeg vil påstå at en litt lettbeint manuell debugging ville ha vist ved inspisering at du sender inn nullobjekter. Når det er sagt så er det vanlig praksis når man gjør validering av data at man antar at dataene ikke er null, for hvis ikke må man nullsjekke hver eneste parameter til alle metoder og skrive fornuftige feilmeldinger for det så blir det dårlig kode. Vi validerer f.eks. at det faktisk er en PDF selv om du sier at det er av type PDF, fordi det er en vanlig feil å sende inn feil dokument. Men å sjekke at det ikke er null har vi ikke sett på som nødvendig, med samme argumentasjon som jeg brukte over.

Derfor, hvis du har et testsystem så bør du selv sørge for å validere data derfra før du sender det videre, eller så kan du komme med en Pull Request på biblioteket. Det er open source og vi tar gjerne imot endringsforespørsler.

En liten gladnyhet på slutten er at siste versjon av klientbiblioteket støtter dotnet-core og om ikke alt for lenge så skal vi få med debug assemblies der slik at man ikke trenger å gjøre slik som du gjør nå.

Håper dette ga deg svar på hvorfor det er som i dag.
