### ISSUE TITLE
Question about digipost xml files

### ISSUE THREAD

**Issue by pebsor** [digipost/digipost-api-client-dotnet#140]
Hi,
I am using the .net client library.
When I retrieve documents from Inbox I only get pdf files.
I do not get XML files with metadata. The inbox itself seems to contain metadata, but this is not the metadata which I got in my documentation from posten.no.

I have read the documentation but I did not find an explanation.

I expected XML like this:

``` xml
<?xml version="1.0"?>
<info>
<kollinr>PU871985588NO</kollinr>        <!-- Dette er sendingsnummeret som dere trolig bør ha ett forhold til -->
<dato>14.06.2018, 13:28</dato>        <!-- Dato og klokkeslett for selve utleveringen -->
<utleveringssted>121502 Coop Extra Rykkinn</utleveringssted>        <!-- Sted for utlevering -->
<kundebehandler>LEDER</kundebehandler>        <!-- Navn på kundebehandler -->
<navndokinnehaver>PLACEBO SPECIMEN</navndokinnehaver>        <!-- Navnet Posten har hentet fra Passet -->
<navnfraedi>PLACEBO SPECIMEN</navnfraedi>        <!-- Navnet banken har sendt oss -->
<fnr>09090512878</fnr>        <!-- Fødselsnummer fra Norsk ID -->
<dnr> </dnr>        <!-- Inntastet Fødselsnummer eller D-nummer fra utenlands ID med tilleggs dok -->
<idtype>Pass</idtype>        <!-- Type ID (dere godkjenner kun Pass) System valg ikke fritekst -->
<doknr>00000000</doknr>        <!-- Pass nummer -->
<utstedt>NOR</utstedt>        <!-- Nasjonalitet på ID bruker en ISO standard på 3 siffer unntatt Tyskland som er D -->
<gyldigtil>011119</gyldigtil>        <!-- Gyldighets dato -->
<tilleggsdok> </tilleggsdok>        <!-- Type tilleggs dok som er forevist Posten med Norsk fødsels/D-nummer -->
<MRZ-kode>PUNOR</MRZ-kode>        <!-- 5 første siffer i MRZ koden (kan brukes til å luke bort Reisebevis, Diplomatpass og utlendingspass etc) -->
<Godkjent>True</Godkjent>        <!-- Om Posten har godkjent utleveringen eller ikke -->
<signaturassistert>False</signaturassistert>        <!-- Universelt utformingskrav at kundebehandler har signert på vegne av kunden, eller holdt hånden e.l. -->
<kontrollstatus>Manuell</kontrollstatus>        <!-- Om Utleveringen er helt Automatisk, eller om noen har gjort manuelt ingripen, Tastat navn. Fødeslnummer etc. manuelt -->
<RFIDlest>False</RFIDlest>        <!-- OM RFID er lest eller ikke             -->
<MRZValid>True</MRZValid>        <!-- MRZ sjekk OK, den sjekkes ganske grundig UV sjekk OK -->
<UVValid>True</UVValid>        <!-- UV lys sjekk OK -->
<IRValid>True</IRValid>        <!-- IR lys sjekk OK -->
<Avbrudsgrunn> </Avbrudsgrunn>        <!-- Fritekst felt en grunn for hvorfor det ble avbrutt utlevering. Skrevet av operatør. Samt noen valgbokser. Denne vil ikke alltid være utfylt -->
</info>
```

**Comment by asjafjell** [comment]
Hi, @pebsor! I am unsure if our API supports delivering the metadata via the inbox API. Maybe @velfundert or @eivinhb has more information on what the API can give out. If that is the case that this can be delivered, then the feature is missing in the client library.

**Comment by velfundert** [comment]
Hi @pebsor!

I took a look at your xml-example, and I do not think that the XML your are looking for is something that Digipost itself is producing, but rather something a separate service is producing, using Digipost as a transport.

Could it be that the XML-files you are looking for are attachments to the pdf-files you are retrieving? I would suggest  checking if your inbox-document contains any attachments of the right type, eg. check the content of `InboxDocument.Attachments`.

**Comment by pebsor** [comment]
Hi,
Thank you. I will try this. I was considering Attachments, but I was 
looking at an item without any attachment; but I can find attachments on 
other items.

Venlig Hilsen/Best Regards
Peter Bo Sørensen



Fra:    Christian S <notifications@github.com>
Til:    digipost/digipost-api-client-dotnet 
<digipost-api-client-dotnet@noreply.github.com>
Cc:     pebsor <pebs@sdc.dk>, Mention <mention@noreply.github.com>
Dato:   06-03-2019 14:46
Emne:   Re: [digipost/digipost-api-client-dotnet] Question about digipost 
xml files (#140)



Hi @pebsor!
I took a look at your xml-example, and I do not think that the XML your 
are looking for is something that Digipost itself is producing, but rather 
something a separate service is producing, using Digipost as a transport.
Could it be that the XML-files you are looking for are attachments to the 
pdf-files you are retrieving? I would suggest checking if your 
inbox-document contains any attachments of the right type, eg. check the 
content of InboxDocument.Attachments.

**Comment by velfundert** [comment]
Hi,

Ok, great! I will close this issue because it is not strictly an issue with the client library. However, if you have any more questions, please don't hesitate to contact us at support@digipost.no 😄 

Best regards
Christian Strandenæs
