### ISSUE TITLE
Get Digipost Address using Personal Identification number 

### ISSUE THREAD

**Issue by Git07Omkar** [digipost/digipost-api-client-dotnet#162]
Hi 
I have followed digipost article - http://digipost.github.io/digipost-api-client-dotnet/v7.0/ and implemented API to get digipost address using the personal identification number.
I am getting the success response but the digipost address is null. 
I have integrated Digipost (Identify recipient through personal identification number) API in my dot net project.

Can you please check and provide me a solution for this? 

the below-mentioned method in the screenshot has been integrated 
![DigipostPIN](https://user-images.githubusercontent.com/48719127/67365918-29fc3100-f590-11e9-937f-e4ebd3904d88.png)

**Comment by AaronArrick** [comment]
Hey there, could you provide what kind of IdentificationResultType you received in your Response?

**Comment by eivinhb** [comment]
Why do you need the digipost address if you have the ssn? We dont give out that kind of information like that.

**Comment by eivinhb** [comment]
Closing because no response.
