### ISSUE TITLE
 Secret Manager i produksjon

### ISSUE THREAD

**Issue by arstad** [digipost/digipost-api-client-dotnet#203]
I dokumentasjonen (https://digipost.github.io/digipost-api-client-dotnet/v14.0/#install-and-use-enterprise-certificate) står følgende:

> The following steps will install the certificate in the your certificate store. This should be done on the server where your application will run. For more information, please see the [Microsoft Documentation](https://docs.microsoft.com/en-us/aspnet/core/security/app-secrets?view=aspnetcore-2.2&tabs=windows#how-the-secret-manager-tool-works).
> 
> The path and password to the certificate must be put somewhere safe.

Linken til dokumentasjonen fra Microsoft vedrørende Secret Manager er tydelig på at Secret Manager er kun tenkt brukt til utviklingsformål og ikke produksjon.

> The Secret Manager tool stores sensitive data during the development of an ASP.NET Core project.

>  Warning
> 
> The Secret Manager tool doesn't encrypt the stored secrets and shouldn't be treated as a trusted store. It's for development purposes only. The keys and values are stored in a JSON configuration file in the user profile directory.

Fins det noen workarounds for å ikke bruke Secret Manager? Hvis ikke vil det blir utviklet?

**Comment by eivinhb** [comment]
Ja, det er en av 3 måter å laste inn sertifikatet på. Jeg er ikke enig i at det kommer utydelig frem at det er ett av flere forslag.
Det er andre kontruktører på DigipostClient også:

https://digipost.github.io/digipost-api-client-dotnet/v14.0/#load-enterprise-certificate-from-file
