### ISSUE TITLE
Logging.log() causes deadlock when LogAction is not defined

### ISSUE THREAD

**Issue by kristianenge** [digipost/digipost-api-client-dotnet#84]
If ClientConfig.Logger is not set the default behavior is to use Logging.ConsoleLogger(). Console.WriteLine is blocking and can cause deadlock.

**Comment by asjafjell** [comment]
Denne er fikset i [7.0.6089.18412-beta](https://www.nuget.org/packages/digipost-api-client/7.0.6089.18412-beta)
