### ISSUE TITLE
Få tak i sertifikater via ApplicationPoolIdentity

### ISSUE THREAD

**Issue by sukchr** [digipost/digipost-api-client-dotnet#87]
Hei, vi kjører vår application pool under Application Pool Identity - http://www.iis.net/learn/manage/configuring-security/application-pool-identities

Så vidt jeg kan se er det ikke mulig å få tak i sertifikater under "Current User" når applikasjonen kjører under Application Pool Identity?

**Comment by asjafjell** [comment]
Hvis det stemmer, så kan du bare laste sertifikatet inn selv. Et eksempel på hvordan dette kan gjøres finner du på [StackOverflow](http://stackoverflow.com/questions/11115511/how-to-find-certificate-by-its-thumbprint-in-c-sharp). Det er bare å bytte `Store.My` og `StoreLocation.CurrentUser`.

**Comment by sukchr** [comment]
Aha, takk! Jeg så ikke at konstruktøren hadde støtte for å sende med et ferdig lastet sertifikat..

**Comment by asjafjell** [comment]
Flott at det ordnet seg!
