### ISSUE TITLE
Thumbprint må være upper-case, uten space

### ISSUE THREAD

**Issue by sukchr** [digipost/digipost-api-client-dotnet#88]
Eksempelet her - http://digipost.github.io/signature-api-client-dotnet/v1.0/#uc01 - antyder at man kan kopiere thumbprint slik den vises i sertifikatdialogen. Det fungerte ikke i mitt tilfelle. Følgende formatering/rensing av thumbprint var nødvendig:

certificateThumbprint = certificateThumbprint.ToUpper();
certificateThumbprint` = new Regex("[^A-Z0-9]").Replace(certificateThumbprint, string.Empty);

**Comment by asjafjell** [comment]
Det kan tilsynelatende se ut til at du må gjøre en slik konvertering for å få det til å fungere, men problemet er nok bare at du har en _Byte Order Mark_ i starten. Hvis du fjerner den så er alt i orden. Se info i [denne posten på StackOverflow](http://stackoverflow.com/a/14852713).

Obs: Ser du poster issues på både `Signatur`-klienten og `Digipost Api`-klienten. Jobber du med begge to? Det er veldig generelle issues du har postet nå, så det gjelder forsåvidt for begge, men det kan hende at ikke gjelder for framtidige spørsmål du måtte ha.

**Comment by sukchr** [comment]
Takk, du har rett. Det var ikke nødvendig med konvertering når byte order mark var fjernet!

Beklager, har nok postet feil sted. Er dette det rette stedet å poste denne typen spørsmål/saker?

**Comment by asjafjell** [comment]
Slik jeg forstår av @mariusbergan så integrerer du mot [Signature Api Client](https://github.com/digipost/signature-api-client-dotnet), så da blir det rett å poste alle issues dit. Dette er klienten for å integrere mot Digipost for å sende brev for private aktører. 

Når det er sagt så er det et veldig tullete problem du opplevde, og en advarsel på akkurat dette har vi glemt å legge inn i denne klienten. Vi blir nok å legge inn et filter som fjerner denne BOMen slik at man slipper å dokumentere det.

Takk!
